name: "Manifest Backward Compatibility Check"
on:
  pull_request:
    types: [opened]

jobs:
  check-manifest-backward-compatibility:
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: xalvarez/prevent-file-change-action@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          pattern: manifest.json

